"""Mock data fixtures generated from real Pulsegrow API responses.

This file contains realistic mock data for use in unit tests.
Generated by scripts/fetch_mock_data.py
"""

ALL_DEVICES = {
    "deviceViewDtos": [
        {
            "deviceType": 1,
            "guid": "0fae1938-f4d6-40ae-9f70-e6a51ff14026",
            "templateId": None,
            "pulseGuid": "8f22fb29-a0bf-445a-9c9f-a95f547b8067",
            "dayStart": "08:00:00",
            "nightStart": "20:00:00",
            "isDay": False,
            "vpdLeafTempOffsetInF": 0,
            "vpdTarget": None,
            "batteryCount": 1,
            "lowBatteryVoltage": 3.7,
            "mostRecentDataPoint": {
                "deviceType": 1,
                "temperatureF": 71.3328,
                "humidityRh": 64.55934,
                "lightLux": 95.6835,
                "airPressure": 94753.5,
                "vpd": 0.93992567,
                "co2": 740,
                "co2Temperature": 24.209579,
                "co2Rh": 54.133606,
                "voc": 0,
                "channel1": 0.25248912,
                "channel2": 0.88693058,
                "channel3": 0.77296478,
                "channel4": 1.8070018,
                "channel5": 3.1238077,
                "channel6": 3.8288221,
                "channel7": 3.6924446,
                "channel8": 1.9388493,
                "near": 0.54765582,
                "clear": 8.14188,
                "flicker": 100,
                "par": 0,
                "gain": 6,
                "tint": 182187.3,
                "deviceId": 20447,
                "pluggedIn": True,
                "batteryV": 4.114231,
                "electricImpId": None,
                "signalStrength": -50,
                "createdAt": "2025-12-29T22:02:33"
            },
            "lastHourData": None,
            "proLightReadingPreviewDto": {
                "id": 433646,
                "ppfd": 264.6240184513413,
                "dli": 11.43,
                "createdAt": "2025-12-28T20:04:55"
            },
            "growTimezoneOffset": -60,
            "id": 20447,
            "displayOrder": 0,
            "name": "PulsePro",
            "growId": 17513,
            "hidden": False
        }
    ],
    "universalSensorViews": [
        {
            "hubId": 402,
            "deviceType": 3,
            "mostRecentDataPoint": {
                "dataPointValues": [
                    {
                        "MeasuringUnit": "",
                        "ParamName": "pH",
                        "ParamValue": "6"
                    }
                ],
                "sensorId": 1638,
                "createdAt": "2025-12-29T22:03:22"
            },
            "sensorType": 3,
            "lastHourDataPointDtos": {
                "dataPointValues": [
                    {
                        "MeasuringUnit": "",
                        "ParamName": "pH",
                        "ParamValues": "6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5.99"
                    }
                ],
                "dataPointValuesCreatedAt": [
                    "2025-12-29T21:04:00Z",
                    "2025-12-29T21:07:01Z",
                    "2025-12-29T21:09:02Z",
                    "2025-12-29T21:12:03Z",
                    "2025-12-29T21:14:04Z",
                    "2025-12-29T21:17:05Z",
                    "2025-12-29T21:20:06Z",
                    "2025-12-29T21:23:07Z",
                    "2025-12-29T21:25:08Z",
                    "2025-12-29T21:28:09Z",
                    "2025-12-29T21:31:10Z",
                    "2025-12-29T21:33:11Z",
                    "2025-12-29T21:36:12Z",
                    "2025-12-29T21:39:13Z",
                    "2025-12-29T21:41:14Z",
                    "2025-12-29T21:44:15Z",
                    "2025-12-29T21:47:16Z",
                    "2025-12-29T21:49:17Z",
                    "2025-12-29T21:52:18Z",
                    "2025-12-29T21:55:19Z",
                    "2025-12-29T21:57:20Z",
                    "2025-12-29T22:00:21Z",
                    "2025-12-29T22:02:22Z"
                ]
            },
            "templateId": None,
            "dayStart": "08:00:00",
            "nightStart": "20:00:00",
            "parSensorSubtype": None,
            "id": 1638,
            "displayOrder": 2,
            "name": "PH Sensor ID: 1638",
            "growId": 17513,
            "hidden": False
        },
        {
            "hubId": 402,
            "deviceType": 3,
            "mostRecentDataPoint": {
                "dataPointValues": [
                    {
                        "MeasuringUnit": "mS/cm",
                        "ParamName": "EC",
                        "ParamValue": "0.8"
                    },
                    {
                        "MeasuringUnit": "\u00b0C",
                        "ParamName": "Temperature",
                        "ParamValue": "22.6"
                    }
                ],
                "sensorId": 1696,
                "createdAt": "2025-12-29T22:03:22"
            },
            "sensorType": 4,
            "lastHourDataPointDtos": {
                "dataPointValues": [
                    {
                        "MeasuringUnit": "mS/cm",
                        "ParamName": "EC",
                        "ParamValues": "0.8, 0.8, 0.8, 0.79, 0.8, 0.79, 0.79, 0.79, 0.79, 0.79, 0.79, 0.79, 0.79, 0.79, 0.79, 0.79, 0.79, 0.79, 0.79, 0.79, 0.79, 0.79, 0.8"
                    },
                    {
                        "MeasuringUnit": "\u00b0C",
                        "ParamName": "Temperature",
                        "ParamValues": "22.3, 22.2, 22.2, 22.2, 22.1, 22.1, 22, 22, 22, 21.9, 21.9, 21.9, 21.8, 21.8, 21.8, 21.8, 21.8, 21.7, 21.7, 21.7, 21.7, 21.5, 22.6"
                    }
                ],
                "dataPointValuesCreatedAt": [
                    "2025-12-29T21:04:00Z",
                    "2025-12-29T21:07:01Z",
                    "2025-12-29T21:09:02Z",
                    "2025-12-29T21:12:03Z",
                    "2025-12-29T21:14:04Z",
                    "2025-12-29T21:17:05Z",
                    "2025-12-29T21:20:06Z",
                    "2025-12-29T21:23:07Z",
                    "2025-12-29T21:25:08Z",
                    "2025-12-29T21:28:09Z",
                    "2025-12-29T21:31:10Z",
                    "2025-12-29T21:33:11Z",
                    "2025-12-29T21:36:12Z",
                    "2025-12-29T21:39:13Z",
                    "2025-12-29T21:41:14Z",
                    "2025-12-29T21:44:15Z",
                    "2025-12-29T21:47:16Z",
                    "2025-12-29T21:49:17Z",
                    "2025-12-29T21:52:18Z",
                    "2025-12-29T21:55:19Z",
                    "2025-12-29T21:57:20Z",
                    "2025-12-29T22:00:21Z",
                    "2025-12-29T22:02:22Z"
                ]
            },
            "templateId": None,
            "dayStart": "08:00:00",
            "nightStart": "20:00:00",
            "parSensorSubtype": None,
            "id": 1696,
            "displayOrder": 3,
            "name": "EC1 Sensor ID: 1696",
            "growId": 17513,
            "hidden": False
        }
    ],
    "hubViewDtos": [
        {
            "deviceType": 2,
            "mostRecentDataPoint": {
                "deviceId": 402,
                "pluggedIn": False,
                "batteryV": 0,
                "electricImpId": None,
                "signalStrength": -55,
                "createdAt": "2025-12-29T22:03:22"
            },
            "id": 402,
            "displayOrder": 1,
            "name": "PulseHub",
            "growId": 17513,
            "hidden": False
        }
    ],
    "controlsViewDtos": []
}

HUB_IDS = [
    402
]

TIMELINE = [
    {
        "id": 42834836,
        "createdAt": "2025-12-29T20:00:38.487",
        "updatedAt": "2025-12-29T20:00:38.487",
        "timelineEventType": 2,
        "title": "Your Nighttime Ph is High  in PH Sensor ID: 1638.",
        "detail": "Reading: 6.5, Limit: 6.4",
        "display": True,
        "growId": 17513
    },
    {
        "id": 42834825,
        "createdAt": "2025-12-29T20:00:03.277",
        "updatedAt": "2025-12-29T20:00:03.277",
        "timelineEventType": 8,
        "title": "PH Sensor ID: 1638 calibrated",
        "detail": "PH Sensor ID: 1638 Id: 1638 has been calibrated for Ph7 ",
        "display": True,
        "growId": 17513
    },
    {
        "id": 42834818,
        "createdAt": "2025-12-29T19:59:20.287",
        "updatedAt": "2025-12-29T19:59:20.287",
        "timelineEventType": 8,
        "title": "PH Sensor ID: 1638 calibrated",
        "detail": "PH Sensor ID: 1638 Id: 1638 has been calibrated for Ph4 ",
        "display": True,
        "growId": 17513
    },
    {
        "id": 42834812,
        "createdAt": "2025-12-29T19:58:58.123",
        "updatedAt": "2025-12-29T19:58:58.123",
        "timelineEventType": 8,
        "title": "PH Sensor ID: 1638 calibrated",
        "detail": "PH Sensor ID: 1638 Id: 1638 has been calibrated for Ph4 ",
        "display": True,
        "growId": 17513
    },
    {
        "id": 42834808,
        "createdAt": "2025-12-29T19:58:36.707",
        "updatedAt": "2025-12-29T19:58:36.707",
        "timelineEventType": 2,
        "title": "Your Nighttime Ph is Low  in PH Sensor ID: 1638.",
        "detail": "Reading: 3.8, Limit: 5.2",
        "display": True,
        "growId": 17513
    },
    {
        "id": 42834795,
        "createdAt": "2025-12-29T19:57:32.317",
        "updatedAt": "2025-12-29T19:57:32.317",
        "timelineEventType": 8,
        "title": "PH Sensor ID: 1638 calibrated",
        "detail": "PH Sensor ID: 1638 Id: 1638 has been calibrated for Ph7 ",
        "display": True,
        "growId": 17513
    },
    {
        "id": 42834790,
        "createdAt": "2025-12-29T19:57:11.377",
        "updatedAt": "2025-12-29T19:57:11.377",
        "timelineEventType": 8,
        "title": "PH Sensor ID: 1638 calibrated",
        "detail": "PH Sensor ID: 1638 Id: 1638 has been calibrated for Ph7 ",
        "display": True,
        "growId": 17513
    },
    {
        "id": 42834766,
        "createdAt": "2025-12-29T19:55:35.583",
        "updatedAt": "2025-12-29T19:55:35.583",
        "timelineEventType": 2,
        "title": "Your Nighttime Ph is High  in PH Sensor ID: 1638.",
        "detail": "Reading: 7, Limit: 6.4",
        "display": True,
        "growId": 17513
    },
    {
        "id": 42830666,
        "createdAt": "2025-12-29T15:41:47.353",
        "updatedAt": "2025-12-29T15:41:47.353",
        "timelineEventType": 2,
        "title": "Your Daytime Co2 is Low in PulsePro.",
        "detail": "Reading: 299, Limit: 300\r\nPush Notification Sent",
        "display": True,
        "growId": 17513
    },
    {
        "id": 42829687,
        "createdAt": "2025-12-29T14:25:44.48",
        "updatedAt": "2025-12-29T14:25:44.48",
        "timelineEventType": 2,
        "title": "Your Daytime Co2 is Low in PulsePro.",
        "detail": "Reading: 299, Limit: 300\r\nPush Notification Sent",
        "display": True,
        "growId": 17513
    },
    {
        "id": 42828350,
        "createdAt": "2025-12-29T12:57:42.77",
        "updatedAt": "2025-12-29T12:57:42.77",
        "timelineEventType": 2,
        "title": "Your Daytime Co2 is Low in PulsePro.",
        "detail": "Reading: 299, Limit: 300\r\nPush Notification Sent",
        "display": True,
        "growId": 17513
    },
    {
        "id": 42825788,
        "createdAt": "2025-12-29T09:35:51.927",
        "updatedAt": "2025-12-29T09:35:51.927",
        "timelineEventType": 2,
        "title": "Your Daytime Ec1Temp is Low  in EC1 Sensor ID: 1696.",
        "detail": "Reading: 67.8, Limit: 20",
        "display": True,
        "growId": 17513
    },
    {
        "id": 42824167,
        "createdAt": "2025-12-29T07:10:38.09",
        "updatedAt": "2025-12-29T07:10:38.09",
        "timelineEventType": 2,
        "title": "Your Daytime Temperature is Low in PulsePro.",
        "detail": "Reading: 64.8, Limit: 68\r\nPush Notification Sent",
        "display": True,
        "growId": 17513
    },
    {
        "id": 42824163,
        "createdAt": "2025-12-29T07:10:37.763",
        "updatedAt": "2025-12-29T07:10:37.763",
        "timelineEventType": 2,
        "title": "Your Daytime Humidity is Low in PulsePro.",
        "detail": "Reading: 36.3, Limit: 40\r\nPush Notification Sent",
        "display": True,
        "growId": 17513
    },
    {
        "id": 42821768,
        "createdAt": "2025-12-29T03:40:36.15",
        "updatedAt": "2025-12-29T03:40:36.15",
        "timelineEventType": 2,
        "title": "Your Nighttime Humidity is Low in PulsePro.",
        "detail": "Reading: 39.9, Limit: 40\r\nPush Notification Sent",
        "display": True,
        "growId": 17513
    },
    {
        "id": 42815187,
        "createdAt": "2025-12-28T19:29:21.27",
        "updatedAt": "2025-12-28T19:29:21.27",
        "timelineEventType": 2,
        "title": "Your Nighttime Temperature is Low in PulsePro.",
        "detail": "Reading: 64.3, Limit: 64.4\r\nPush Notification Sent",
        "display": True,
        "growId": 17513
    },
    {
        "id": 42814890,
        "createdAt": "2025-12-28T19:10:21.657",
        "updatedAt": "2025-12-28T19:10:21.657",
        "timelineEventType": 2,
        "title": "Your Nighttime Humidity is Low in PulsePro.",
        "detail": "Reading: 32.4, Limit: 40\r\nPush Notification Sent",
        "display": True,
        "growId": 17513
    },
    {
        "id": 42813819,
        "createdAt": "2025-12-28T17:31:19.263",
        "updatedAt": "2025-12-28T17:31:19.263",
        "timelineEventType": 2,
        "title": "Your Daytime Temperature is Low in PulsePro.",
        "detail": "Reading: 68, Limit: 68\r\nPush Notification Sent",
        "display": True,
        "growId": 17513
    },
    {
        "id": 42812979,
        "createdAt": "2025-12-28T16:18:20.797",
        "updatedAt": "2025-12-28T16:18:20.797",
        "timelineEventType": 2,
        "title": "Your Daytime Temperature is Low in PulsePro.",
        "detail": "Reading: 68, Limit: 68\r\nPush Notification Sent",
        "display": True,
        "growId": 17513
    },
    {
        "id": 42811992,
        "createdAt": "2025-12-28T15:05:18.507",
        "updatedAt": "2025-12-28T15:05:18.507",
        "timelineEventType": 2,
        "title": "Your Daytime Temperature is Low in PulsePro.",
        "detail": "Reading: 68, Limit: 68\r\nPush Notification Sent",
        "display": True,
        "growId": 17513
    },
    {
        "id": 42810957,
        "createdAt": "2025-12-28T13:33:16.997",
        "updatedAt": "2025-12-28T13:33:16.997",
        "timelineEventType": 2,
        "title": "Your Daytime Temperature is Low in PulsePro.",
        "detail": "Reading: 68, Limit: 68\r\nPush Notification Sent",
        "display": True,
        "growId": 17513
    },
    {
        "id": 42810375,
        "createdAt": "2025-12-28T13:01:17.93",
        "updatedAt": "2025-12-28T13:01:17.93",
        "timelineEventType": 2,
        "title": "Your Daytime Co2 is Low in PulsePro.",
        "detail": "Reading: 298, Limit: 300\r\nPush Notification Sent",
        "display": True,
        "growId": 17513
    },
    {
        "id": 42809937,
        "createdAt": "2025-12-28T12:17:15.663",
        "updatedAt": "2025-12-28T12:17:15.663",
        "timelineEventType": 2,
        "title": "Your Daytime Temperature is Low in PulsePro.",
        "detail": "Reading: 68, Limit: 68\r\nPush Notification Sent",
        "display": True,
        "growId": 17513
    },
    {
        "id": 42808583,
        "createdAt": "2025-12-28T10:45:13.227",
        "updatedAt": "2025-12-28T10:45:13.227",
        "timelineEventType": 2,
        "title": "Your Daytime Temperature is Low in PulsePro.",
        "detail": "Reading: 68, Limit: 68\r\nPush Notification Sent",
        "display": True,
        "growId": 17513
    },
    {
        "id": 42807692,
        "createdAt": "2025-12-28T09:33:12.713",
        "updatedAt": "2025-12-28T09:33:12.713",
        "timelineEventType": 2,
        "title": "Your Daytime Temperature is Low in PulsePro.",
        "detail": "Reading: 68, Limit: 68\r\nPush Notification Sent",
        "display": True,
        "growId": 17513
    },
    {
        "id": 42807257,
        "createdAt": "2025-12-28T08:57:12.827",
        "updatedAt": "2025-12-28T08:57:12.827",
        "timelineEventType": 2,
        "title": "Your Daytime Co2 is Low in PulsePro.",
        "detail": "Reading: 298, Limit: 300\r\nPush Notification Sent",
        "display": True,
        "growId": 17513
    },
    {
        "id": 42806552,
        "createdAt": "2025-12-28T07:47:11.293",
        "updatedAt": "2025-12-28T07:47:11.293",
        "timelineEventType": 2,
        "title": "Your Daytime Co2 is Low in PulsePro.",
        "detail": "Reading: 299, Limit: 300\r\nPush Notification Sent",
        "display": True,
        "growId": 17513
    },
    {
        "id": 42806227,
        "createdAt": "2025-12-28T07:11:10.81",
        "updatedAt": "2025-12-28T07:11:10.81",
        "timelineEventType": 2,
        "title": "Your Daytime Temperature is Low in PulsePro.",
        "detail": "Reading: 67.7, Limit: 68\r\nPush Notification Sent",
        "display": True,
        "growId": 17513
    },
    {
        "id": 42806226,
        "createdAt": "2025-12-28T07:11:10.463",
        "updatedAt": "2025-12-28T07:11:10.463",
        "timelineEventType": 2,
        "title": "Your Daytime Humidity is Low in PulsePro.",
        "detail": "Reading: 30.3, Limit: 40\r\nPush Notification Sent",
        "display": True,
        "growId": 17513
    },
    {
        "id": 42805906,
        "createdAt": "2025-12-28T06:44:10.063",
        "updatedAt": "2025-12-28T06:44:10.063",
        "timelineEventType": 2,
        "title": "Your Nighttime Co2 is Low in PulsePro.",
        "detail": "Reading: 299, Limit: 300\r\nPush Notification Sent",
        "display": True,
        "growId": 17513
    },
    {
        "id": 42797507,
        "createdAt": "2025-12-27T19:51:01.837",
        "updatedAt": "2025-12-27T19:51:01.837",
        "timelineEventType": 2,
        "title": "Your Nighttime Humidity is Low in PulsePro.",
        "detail": "Reading: 31.1, Limit: 40\r\nPush Notification Sent",
        "display": True,
        "growId": 17513
    },
    {
        "id": 42797504,
        "createdAt": "2025-12-27T19:50:51.48",
        "updatedAt": "2025-12-27T19:50:51.48",
        "timelineEventType": 2,
        "title": "PulsePro recovered from power loss",
        "detail": "Device: PulsePro recovered from a power event, possibly an outage.\r\nPush Notification Sent",
        "display": True,
        "growId": 17513
    }
]

TRIGGERED_THRESHOLDS = {
    "ongoing": [],
    "resolved": [
        {
            "id": 1229890,
            "createdAt": "2025-12-29T20:00:38.209952",
            "resolvedAt": "2025-12-29T20:01:37.4892324",
            "resolved": False,
            "thresholdId": None,
            "thresholdType": None,
            "deviceId": 1638,
            "deviceName": "PH Sensor ID: 1638",
            "lowOrHigh": True,
            "lowThresholdValue": 5.2,
            "highThresholdValue": 6.4,
            "triggeringValue": "6.5",
            "sensorThresholdType": 6,
            "hubThresholdType": None
        },
        {
            "id": 1229885,
            "createdAt": "2025-12-29T19:58:36.3714755",
            "resolvedAt": "2025-12-29T19:59:36.7721423",
            "resolved": False,
            "thresholdId": None,
            "thresholdType": None,
            "deviceId": 1638,
            "deviceName": "PH Sensor ID: 1638",
            "lowOrHigh": False,
            "lowThresholdValue": 5.2,
            "highThresholdValue": 6.4,
            "triggeringValue": "3.8",
            "sensorThresholdType": 6,
            "hubThresholdType": None
        },
        {
            "id": 1229880,
            "createdAt": "2025-12-29T19:55:35.2579364",
            "resolvedAt": "2025-12-29T19:58:36.3653118",
            "resolved": False,
            "thresholdId": None,
            "thresholdType": None,
            "deviceId": 1638,
            "deviceName": "PH Sensor ID: 1638",
            "lowOrHigh": True,
            "lowThresholdValue": 5.2,
            "highThresholdValue": 6.4,
            "triggeringValue": "7",
            "sensorThresholdType": 6,
            "hubThresholdType": None
        },
        {
            "id": 117413068,
            "createdAt": "2025-12-29T15:53:46.71",
            "resolvedAt": "2025-12-29T15:55:44.477",
            "resolved": False,
            "thresholdId": 320093,
            "thresholdType": 7,
            "deviceId": 20447,
            "deviceName": "PulsePro",
            "lowOrHigh": False,
            "lowThresholdValue": 300,
            "highThresholdValue": 2400,
            "triggeringValue": "299",
            "sensorThresholdType": None,
            "hubThresholdType": None
        },
        {
            "id": 117412672,
            "createdAt": "2025-12-29T15:41:46.78",
            "resolvedAt": "2025-12-29T15:43:45.373",
            "resolved": False,
            "thresholdId": 320093,
            "thresholdType": 7,
            "deviceId": 20447,
            "deviceName": "PulsePro",
            "lowOrHigh": False,
            "lowThresholdValue": 300,
            "highThresholdValue": 2400,
            "triggeringValue": "299",
            "sensorThresholdType": None,
            "hubThresholdType": None
        },
        {
            "id": 117411314,
            "createdAt": "2025-12-29T15:05:44.2",
            "resolvedAt": "2025-12-29T15:08:45.18",
            "resolved": False,
            "thresholdId": 320093,
            "thresholdType": 7,
            "deviceId": 20447,
            "deviceName": "PulsePro",
            "lowOrHigh": False,
            "lowThresholdValue": 300,
            "highThresholdValue": 2400,
            "triggeringValue": "299",
            "sensorThresholdType": None,
            "hubThresholdType": None
        },
        {
            "id": 117411043,
            "createdAt": "2025-12-29T14:56:44.827",
            "resolvedAt": "2025-12-29T15:02:45.373",
            "resolved": False,
            "thresholdId": 320093,
            "thresholdType": 7,
            "deviceId": 20447,
            "deviceName": "PulsePro",
            "lowOrHigh": False,
            "lowThresholdValue": 300,
            "highThresholdValue": 2400,
            "triggeringValue": "299",
            "sensorThresholdType": None,
            "hubThresholdType": None
        },
        {
            "id": 117410081,
            "createdAt": "2025-12-29T14:25:43.693",
            "resolvedAt": "2025-12-29T14:32:43.373",
            "resolved": False,
            "thresholdId": 320093,
            "thresholdType": 7,
            "deviceId": 20447,
            "deviceName": "PulsePro",
            "lowOrHigh": False,
            "lowThresholdValue": 300,
            "highThresholdValue": 2400,
            "triggeringValue": "299",
            "sensorThresholdType": None,
            "hubThresholdType": None
        },
        {
            "id": 117408596,
            "createdAt": "2025-12-29T13:43:42.6",
            "resolvedAt": "2025-12-29T13:47:44.307",
            "resolved": False,
            "thresholdId": 320093,
            "thresholdType": 7,
            "deviceId": 20447,
            "deviceName": "PulsePro",
            "lowOrHigh": False,
            "lowThresholdValue": 300,
            "highThresholdValue": 2400,
            "triggeringValue": "299",
            "sensorThresholdType": None,
            "hubThresholdType": None
        },
        {
            "id": 117406842,
            "createdAt": "2025-12-29T12:57:41.9",
            "resolvedAt": "2025-12-29T13:33:44.453",
            "resolved": False,
            "thresholdId": 320093,
            "thresholdType": 7,
            "deviceId": 20447,
            "deviceName": "PulsePro",
            "lowOrHigh": False,
            "lowThresholdValue": 300,
            "highThresholdValue": 2400,
            "triggeringValue": "299",
            "sensorThresholdType": None,
            "hubThresholdType": None
        }
    ],
    "growId": 17513
}

USER_USAGE = [
    {
        "userId": 17425,
        "userEmail": "pascal@vizeli.ch",
        "userName": "pascal@vizeli.ch",
        "lastActive": "2025-12-29T17:20:37.6",
        "role": "Owner"
    }
]

HUB_DETAILS = {
    "id": 402,
    "name": "PulseHub",
    "hubThresholds": [
        {
            "hubId": 402,
            "thresholdType": 2,
            "id": 805,
            "notificationActive": False,
            "lowThresholdValue": None,
            "highThresholdValue": None,
            "delay": "00:03:00",
            "day": None
        },
        {
            "hubId": 402,
            "thresholdType": 1,
            "id": 806,
            "notificationActive": False,
            "lowThresholdValue": None,
            "highThresholdValue": None,
            "delay": "00:00:00",
            "day": None
        }
    ],
    "hidden": False,
    "macAddress": "0c2a6914e40e",
    "growId": 17513,
    "sensorDevices": [
        {
            "hubId": 402,
            "parSensorSubtype": None,
            "deviceType": 3,
            "sensorType": 3,
            "id": 1638,
            "displayOrder": 2,
            "name": "PH Sensor ID: 1638",
            "growId": 17513,
            "hidden": False
        },
        {
            "hubId": 402,
            "parSensorSubtype": None,
            "deviceType": 3,
            "sensorType": 4,
            "id": 1696,
            "displayOrder": 3,
            "name": "EC1 Sensor ID: 1696",
            "growId": 17513,
            "hidden": False
        }
    ]
}

